local o = vim.opt

o.number = true
o.relativenumber = true
o.mouse = "a"
o.clipboard = "unnamedplus" -- Use system clipboard
o.swapfile = false
o.backup = false
o.undofile = true           -- Persistent undo
o.wrap = false
o.expandtab = true       -- Use spaces instead of tabs
o.shiftwidth = 2        -- Size of an indent
o.tabstop = 2           -- Number of spaces tabs count for
o.softtabstop = 2       -- Makes backspace feel normal
o.smartindent = true    -- Auto-indent new lines
o.autoindent = true     -- Keep indent of current line
o.signcolumn = "yes"
o.termguicolors = true
o.ignorecase = true
o.smartcase = true      -- Overrides ignorecase if search has capitals
o.incsearch = true      -- Show matches as you type
o.hlsearch = true       -- Highlight all matches
o.cursorline = true
o.splitright = true
o.splitbelow = true
o.updatetime = 250      -- Faster CursorHold events
o.timeoutlen = 400      -- Time to wait for mapped sequence
o.lazyredraw = true     -- Don't redraw during macros
o.synmaxcol = 240       -- Stop syntax highlight past X chars
